### ISSUE TITLE
Doublon sur la page des recrutements

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#12]
**Date**
30/05/19 13:54

**Type de compte**
Pompier

**Description du bug**
Bonjour,

Sur la page des recrutement, j'ai deux bouton "recruter SPV"

Cordialement,

**Reproduction**

**Comportement attendu**

**Screenshots**
https://goopics.net/i/nQg5b

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
CDT Maxime PAPUCHE

**Comment by StevenSoulet** [comment]
Corrigé
