### ISSUE TITLE
Perte d'accée au PV non Trensferer

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#23]
**Date**
12/06/19 12:19

**Type de compte**
Tribunal

**Description du bug**
Tout es dans le titre mes louliu <3

**Reproduction**

**Comportement attendu**
Baaa qu'on y es de nouveau accées :D

**Screenshots**

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
SUB. Tai LASTIMOSA

**Comment by StevenSoulet** [comment]
L'ajout de la ligne : ->andWhere("unit.abrv != 'IGGN'");
Fait disparaître tous les PV

**Comment by AlbeBertin** [comment]
Rajouter un orWhere(unit is null)
