### ISSUE TITLE
Probléme a la fermeture du PV

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#24]
**Date**
12/06/19 22:50

**Type de compte**
Tribunal

**Description du bug**
Bonsoir, nous venons de finir un Jugement donc j'ai bien fais ce qui étais à faire, mettre le PV "En cours de Jugement" mais au moment de terminer une page d'érreur es apparue (la page qui dis que j'ai pas les autorisation pour faire ça) mais le PV et quand même déplacer en "Terminer" Mais une fois fait il es pas possible de mettre une compte rendue de jugement.

PS: Si pour mettre le compte rendue ded jugement il faut le faire avant de terminer le PV merci de me le dire :D

**Reproduction**
Passer le PV "en cours de jugement" cliquer sur "Terminer" la page d’erreur devrais apparaître et on ne peut pas mettre de compte rendue de jugement 

**Comportement attendu**
De ne pas avoir la page "d'erreur" et de pouvoir mettre le compte rendue de jugement une vois le PV terminer

**Screenshots**
J'ai pas penser a en faire déso 

**Navigateur:**
Chrome (PC)

**Autre**
Euh .... Pokemon Go !!!!

**Auteur**
SUB. Tai LASTIMOSA

**Comment by AlbeBertin** [comment]
Problème de changement de status (Ce PV n'est pas en cours de jugement).

**Comment by AlbeBertin** [comment]
Par contre c'est vraiment un jeu de merde Poemon Go... Déçu du tribunal.

**Comment by StevenSoulet** [comment]
Après vérification, aucun problème, le PV se clôture correctement, les conditions sont correctes.

**Comment by AlbeBertin** [comment]
Je pense que c'est parce qu'il a du cliquer 2 fois en même temps, et donc la 2e fois le PV était Terminé et donc pas possible de le repasser en Terminé.
