### ISSUE TITLE
Probleme validation convocation 

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#28]
**Date**
16/06/19 13:04

**Type de compte**
Tribunal

**Description du bug**
Alors que nous voulons validé que la convocation a bien étais envoyer https://i.goopics.net/Xjd3q.png cela nous demande d'appuyé sur ok et par la suite cela nous renvoie sur une autre page 'procès verbaux' 

**Reproduction**
Nous allons sur pv , ensuite nous cliquons sur les personne que nous avons avant convoqué pour la suite validé les convocation bien envoyé. 
Sa nous demande par la suite d'appuyé sur ok . 
Et par la suite sa nous envoie sur procès verbaux

**Comportement attendu**
La validation de la convocation pour moi devrai juste validée que nous avons bien convoqué et ne pas renvoyé sur un lien . Ainsi nos pv ne se retrouverai pas a changer de couleur car nous arrivons sur la limite du temps d'envoyé nos convocations  chose que nous avons fait .

**Screenshots**
https://i.goopics.net/Xjd3q.png , https://i.goopics.net/deYoy.png

**Navigateur:**
Firefox

**Autre**

**Auteur**
P.R Artheon DENZA

**Comment by StevenSoulet** [comment]
@AlbeBertin C'est quoi l'utilité du bouton ? Je trouve rien dans les controllers qui peux correspondre

**Comment by AlbeBertin** [comment]
Je sais pas si j'avais fini... C'est de mettre la fiche PV en convoqué, pour que ça s'affiche sur la liste des personnes impliquées

**Comment by AlbeBertin** [comment]
Faudrait rediriger sur la fiche PV quand on a changé le statut de convocation de la personne

**Comment by AlbeBertin** [comment]
Et enlever la couleur de la limitation du temps

**Comment by StevenSoulet** [comment]
Couleur de la limitation du temps ? ou sa ?

**Comment by AlbeBertin** [comment]
Avant, il y avait une histoire de temps limite avant de convoquer.

**Comment by AlbeBertin** [comment]
Avant, il y avait une histoire de temps limite avant de convoquer.
