### ISSUE TITLE
Pas de son lors du BIP SP

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#31]
**Date**
17/06/19 20:21

**Type de compte**
Pompier

**Description du bug**
Quand on envoie un  message au personnel en astreinte, on reçoit de l’alerte mais ça ne sonne pas. 

**Reproduction**

**Comportement attendu**
Bha avoir le bip bip X)

**Screenshots**

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
CDT Maxime PAPUCHE

**Comment by StevenSoulet** [comment]
Le personnel qui reçois 'lalerte dois activer le son depuis son menu sur l'intranet

**Comment by AlbeBertin** [comment]
Nope, normalement le son pour les astreintes est automatique.

Mais c'est sûrement tout cassé car les navigateurs n'autorisent plus à jouer des sons en background...

**Comment by StevenSoulet** [comment]
Ducou c'est pas de notre ressort, j'archive et on verra si on met un nouveau système.

**Comment by AlbeBertin** [comment]
Faudrait tester sur Lifeshare si les notifications sonores en background fonctionnent et si oui, je regarderai comment c'est fait.
