### ISSUE TITLE
COG sans patrouille ne s'indiquant pas

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#32]
**Date**
17/06/19 20:26

**Type de compte**
Gendarmerie

**Description du bug**
Quand j'indique un COG, par exemple le https://intranet.arma3lifefrance.fr/Gendarmerie/COG/3
celui s'enregistre correctement s'il n'y a pas de patrouille envoyée. 

Cependant, il ne s'affiche pas dans la liste des COG

**Reproduction**
Réitération

**Comportement attendu**
Affichage dans la liste

**Screenshots**

**Navigateur:**
Firefox

**Autre**

**Auteur**
ELG Charlie ROMEO

**Comment by AlbeBertin** [comment]
Étrange...

**Comment by StevenSoulet** [comment]
J'ai tester plein de truc dans le code je comprend pas pourquoi...

**Comment by AlbeBertin** [comment]
C'est avéré comme bug ?

**Comment by AlbeBertin** [comment]
Corrigé!
