### ISSUE TITLE
Erreurs SQL

### ISSUE THREAD

**Issue by StevenSoulet** [AlbeBertin/ALF-Bugs#33]
Lors de la suppression d'une GAV :
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`armalifejqintra`.`user`, CONSTRAINT `FK_8D93D649B5B2F6A9` FOREIGN KEY (`fiche_prison_id`) REFERENCES `prison` (`id`))

Lors de la création d'une GAV : 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'UNIQ_8D93D649B5B2F6A9'

**Comment by AlbeBertin** [comment]
Ça.est parce que tu as mal clean la DB de test.
Regarde la table user : il doit y avoir un individu qui a comme fiche_prison_id 3.
Et pareil pour la création.

**Comment by AlbeBertin** [comment]
Toujours activer les clés étrangères :wink:

**Comment by StevenSoulet** [comment]
Ah merde, je règle sa comment ? Car la sa risque aps de foutre la merde ? J'ai mis fin aux GAV

**Comment by StevenSoulet** [comment]
Réglé
