### ISSUE TITLE
Retard impôts (Suggestion)

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#34]
**Date**
19/06/19 18:47

**Type de compte**
Préfecture

**Description du bug**
Comme vu avec vous, j'aimerai savoir s'il est possible d'avoir une fonctionnalité pour le Préfet afin de remettre à 0 les jours de retard côté imposition (cf screen)

**Reproduction**

**Comportement attendu**

**Screenshots**
http://prntscr.com/o3zhwj

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
Préfet Elisabeth ALARACH

**Comment by StevenSoulet** [comment]
Le nombre de jour de retard se calcule automatiquement en rapport avec la date de création, la dernière déclaration, et la date du jours.

**Comment by AlbeBertin** [comment]
Entreprise::lastDeclaredAt (datetime).

Initialiser dans le construct.
Nouvelle déclaration : mettre à jour. 

Action pour officiers : réinitialiser à la date actuelle.
