### ISSUE TITLE
Fin FPR gendarmerie

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#39]
**Date**
24/06/19 20:08

**Type de compte**
Gendarmerie

**Description du bug**
Nous ne pouvons pas mettre fin au FPR d'une personne.

**Reproduction**

**Comportement attendu**

**Screenshots**

**Navigateur:**
Safari (PC)

**Autre**

**Auteur**
MDC Antonio BIONDEL

**Comment by AlbeBertin** [comment]
Confirmé ? Je l'ai fix hier normalement

**Comment by StevenSoulet** [comment]
Je comprend pas, sa dis que la route n'existe pas alors qu'elle est OK

**Comment by AlbeBertin** [comment]
Même avec ce commit ? ced58abcd627802f18c2300eb97646c6ca7de155

**Comment by AlbeBertin** [comment]
Vérifie l'URL sur le CelluleRens Controller.

**Comment by AlbeBertin** [comment]
On ne peut pas faire de FPR aussi. Problème de méthode : faut accepter GET et POST.

**Comment by StevenSoulet** [comment]
Création FPR fix.
