### ISSUE TITLE
Problème message

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#4]
**Date**
18/04/19 19:59

**Type de compte**
Gendarmerie

**Description du bug**
Les images ne s'affichent pas

**Reproduction**

**Comportement attendu**

**Screenshots**
http://servicespublicsalf.online/Messages/81

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
GND Mathis SAWN

**Comment by StevenSoulet** [comment]
Liens images HS

**Comment by AlbeBertin** [comment]
Effectivement, j'ai supprimé le Sheet qui contenait ces images...

**Comment by StevenSoulet** [comment]
Corrigé, images mises à jours.
