### ISSUE TITLE
Probleme d'ouverture de PV

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#5]
**Date**
20/04/19 22:45

**Type de compte**
Gendarmerie

**Description du bug**
Ouverture de PV impossible

**Reproduction**

**Comportement attendu**
Reglage du probleme

**Screenshots**

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
SLT Mike ABAGNALE

**Comment by AlbeBertin** [comment]
Cf logs serveur : problème sur la requête pour le nouveau numéro du PV

Checker version mysql ALF (hypothèse : CAST pas disponible)

**Comment by StevenSoulet** [comment]
"Nanou": je sais pas trop mais si c'est sur OVH c'est du 5.16
A vérifier car info non validée.

**Comment by AlbeBertin** [comment]
Visiblement, CAST peut être utilisé en 5.1... Essaie de demander à Alejandro.

Je cherche une alternative

**Comment by AlbeBertin** [comment]
Corrigé!

**Comment by AlbeBertin** [comment]
Corrigé!
