### ISSUE TITLE
Bug d'affichange - Panel admin

### ISSUE THREAD

**Issue by AlbeBertin** [AlbeBertin/ALF-Bugs#6]
**Date**
21/04/19 21:07

**Type de compte**
Gendarmerie

**Description du bug**
Côté panel admin bug d'affichage dans les menus.
Une partie de l'affichage n’apparaît pas. En cliquant sur les onglets à gauche, on arrive à avoir la suite de l'affichage, mais pas toujours. (Voir screen)

Berto.

**Reproduction**

**Comportement attendu**

**Screenshots**
1. https://i.gyazo.com/a1e932851a6316eeccf3f5a75c70b274.png
2. https://i.gyazo.com/9cd0369ca4dd4a5e1170964df7473199.png
3. 

**Navigateur:**
Chrome (PC)

**Autre**

**Auteur**
LCL Giovanni BERTONI

**Comment by StevenSoulet** [comment]
Pris en compte, en cours d’etude.
